### ISSUE TITLE
Data types

### ISSUE THREAD

**Issue by TimPietrusky** [failfa-st/prompt-my-docs#1]
- [ ] Collect the data types that the community needs and add them into **Prompt my Docs**
- [ ] Documentation about the data types in README
- [x] Show all "included" types

## Included

* md
* js
* ts

## Roadmap

* PDF (planned)

## What else?

Please let me know, then we will extend the list of data types for **Prompt my Docs**.
